Employee Number,Last Name,First Name,Date of birth,Gender,Tobacco used in last 12 months,Relation
1001,Test,User,21/4/1990,Male,FALSE,Subscriber
1002,Test2,user2,21/4/1992,Male,FALSE,Subscriber
1003,Test3,user3,21/4/1980,Female,FALSE,Subscriber
1004,Test6,user4,21/4/1980,Male,FALSE,Subscriber
1004,Test7,user5,21/4/1991,Male,FALSE,Dependent
1004,Test 6,User,21/4/1992,Female,FALSE,Spouse
1005,Test,User5,21/4/1960,Male,FALSE,Subscriber
1006,Test,User5,21/4/1975,Male,FALSE,Subscriber
1007,Test,User5,21/4/1980,Male,FALSE,Subscriber
1008,Test,User5,21/4/1982,Male,FALSE,Subscriber
1009,Test,User5,21/4/1971,Male,FALSE,Subscriber
1010,Test,User5,21/4/1993,Male,FALSE,Subscriber
1011,Test,User5,21/4/1964,Male,FALSE,Subscriber
